# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://:action_cable@pub-redis-13358.us-east-1-2.1.ec2.garantiadata.com:13358

development:
  adapter: async

test:
  adapter: async
